Modern theme support for tile component
blackbaud/skyux-tiles pull request #75
Opened 2021-03-01 17:58 UTC by Blackbaud-AlexKingman

https://blackbaud.invisionapp.com/console/share/UG1N3XTCC7/483430271

2021-03-01 18:17 UTC, blackbaud-ado commented
Preview build at [https://developer.blackbaud.com/skyux-tiles?_sp.spa=pr-tile-modern-theme](https://developer.blackbaud.com/skyux-tiles?_sp.spa=pr-tile-modern-theme)

2021-03-11 20:43 UTC, blackbaud-ado commented
Preview build at [https://developer.blackbaud.com/skyux-tiles?_sp.spa=pr-tile-modern-theme](https://developer.blackbaud.com/skyux-tiles?_sp.spa=pr-tile-modern-theme)

2021-03-11 21:48 UTC, blackbaud-ado commented
Preview build at [https://developer.blackbaud.com/skyux-tiles?_sp.spa=pr-tile-modern-theme](https://developer.blackbaud.com/skyux-tiles?_sp.spa=pr-tile-modern-theme)

2021-03-17 14:49 UTC, blackbaud-ado commented
Preview build at [https://developer.blackbaud.com/skyux-tiles?_sp.spa=pr-tile-modern-theme](https://developer.blackbaud.com/skyux-tiles?_sp.spa=pr-tile-modern-theme)

2021-03-17 16:42 UTC, blackbaud-ado commented
Preview build at [https://developer.blackbaud.com/skyux-tiles?_sp.spa=pr-tile-modern-theme](https://developer.blackbaud.com/skyux-tiles?_sp.spa=pr-tile-modern-theme)

2021-03-18 15:31 UTC, Blackbaud-ToddRoberts commented
The header buttons (except for chevron) need to be updated to match borderless icon button (size is wrong, can't tell about color)

2021-03-18 18:56 UTC, Blackbaud-AlexKingman commented
> The header buttons (except for chevron) need to be updated to match borderless icon button (size is wrong, can't tell about color)

Looks like there were some other styles overriding sizes. I've fixed that now and ensured everything has the borderless icons styles. Although, it does seem like they're not the same size - especially the grid icon. Even though they're all 16px, it seems a little of.... Is this how it's supposed to look?
![Screen Shot 2021-03-18 at 2 54 40 PM](https://user-images.githubusercontent.com/18354182/111681778-04fa0500-87fa-11eb-82b3-4a1c8c23475a.png)

2021-03-18 19:04 UTC, blackbaud-ado commented
Preview build at [https://developer.blackbaud.com/skyux-tiles?_sp.spa=pr-tile-modern-theme](https://developer.blackbaud.com/skyux-tiles?_sp.spa=pr-tile-modern-theme)

2021-03-18 19:24 UTC, Blackbaud-ToddRoberts commented
I believe the drag icon has an update in the latest icons PR to make it larger, currently it does render smaller than the other icons.

2021-03-18 19:40 UTC, Blackbaud-ToddRoberts commented
Also need 10px of margin between the buttons - with the small size, the spacing is important to allow accurate click targeting.

2021-03-22 20:46 UTC, blackbaud-ado commented
Preview build at [https://developer.blackbaud.com/skyux-tiles?_sp.spa=pr-tile-modern-theme](https://developer.blackbaud.com/skyux-tiles?_sp.spa=pr-tile-modern-theme)

2021-03-22 20:55 UTC, Blackbaud-ToddRoberts requested changes
Spacing between tiles needs to be updated to 30px to match modern spacing guidelines

2021-03-23 14:04 UTC, blackbaud-ado commented
Preview build at [https://developer.blackbaud.com/skyux-tiles?_sp.spa=pr-tile-modern-theme](https://developer.blackbaud.com/skyux-tiles?_sp.spa=pr-tile-modern-theme)

2021-03-24 00:13 UTC, blackbaud-ado commented
Preview build at [https://developer.blackbaud.com/skyux-tiles?_sp.spa=pr-tile-modern-theme](https://developer.blackbaud.com/skyux-tiles?_sp.spa=pr-tile-modern-theme)

2021-03-24 12:56 UTC, Blackbaud-ToddRoberts approved these changes

2021-03-24 17:19 UTC, Blackbaud-SteveBrush reviewed
One small thing. Are we not disabling view encapsulation for this component?

2021-03-24 17:19 UTC, Blackbaud-SteveBrush commented on src/app/public/modules/tiles/tile-dashboard/tile-dashboard.component.spec.ts
> +import { TileDashboardOnPushTestComponent
Import style.

2021-03-24 19:25 UTC, Blackbaud-AlexKingman commented on src/app/public/modules/tiles/tile-dashboard/tile-dashboard.component.spec.ts
> +import { TileDashboardOnPushTestComponent
Fixed.

2021-03-24 19:27 UTC, Blackbaud-AlexKingman commented
> Are we not disabling view encapsulation for this component?

Good question. I didn't have to write any *new* styles that used `ng-deep`. I just had to overwrite some styles that were already using `ng-deep`. While tiles uses this pattern sometimes, it wasn't nearly as bad as some of the other modern upgraded. I'm on the fence about removing encapsulation, but could be persuaded.
Do you have strong feelings on it?

2021-03-24 19:39 UTC, blackbaud-ado commented
Preview build at [https://developer.blackbaud.com/skyux-tiles?_sp.spa=pr-tile-modern-theme](https://developer.blackbaud.com/skyux-tiles?_sp.spa=pr-tile-modern-theme)

2021-03-25 13:25 UTC, Blackbaud-SteveBrush approved these changes

2021-03-25 13:26 UTC, merged